name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Clean up
        run: make clean
      - name: make
        run: make
      - name: Run hello script
        run: echo "Hello, world!"
      - name: show folder content
        run: ls -la  
      - name: show file type
        run: file main
      - name: show system specs
        run: lscpu

