name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make
      run: make
      - name: Install dependencies
        run: sudo apt-get install -y build-essential

      - name: Compile main.cpp
        run: g++ -o main main.cpp

      - name: Run executable
        run: ./main


